-- SQL Portfolio: Aggregate Functions & Basic Arithmetic Queries
-- Dataset: Dunder Mifflin Paper Sales
-- Purpose: Demonstrate use of SQL aggregate functions to answer business questions related to revenue, pricing, and performance.


---------------------------------------------------
-- SECTION 1: Aggregate Fuctions (Q1–Q10)
---------------------------------------------------


-- Question #1: What is the average order price across all orders?
SELECT ROUND(AVG(price * quantity), 2) AS avg_order_price
FROM tutorial.dunder_mifflin_paper_sales;

---------------------------------------------------

-- Question #2: What is the total revenue generated by each account?
SELECT
  account_name,
  SUM((price * quantity) - discount) AS total_revenue
FROM tutorial.dunder_mifflin_paper_sales
WHERE discount IS NOT NULL     -- Orders with NULL discount values are excluded due to missing data.
GROUP BY account_name
ORDER BY total_revenue DESC;

---------------------------------------------------

-- Question #3: What are the minimum and maximun product prices in the dataset?
SELECT 
  MIN(price) AS minimum_product_price,
  MAX(price) AS maximum_product_price
FROM tutorial.dunder_mifflin_paper_sales;

---------------------------------------------------

-- Question #4: What is the average discount applies across all orders?
SELECT ROUND(AVG(discount), 2) AS avg_discount
FROM tutorial.dunder_mifflin_paper_sales
WHERE discount IS NOT NULL;     -- Orders with NULL discount values are excluded due to missing data.

---------------------------------------------------

-- Question #5: How much total revenue comes from each shipping region?
SELECT 
  shipping_region,
  SUM(price * quantity) AS total_regional_revenue
FROM tutorial.dunder_mifflin_paper_sales
GROUP BY shipping_region
ORDER BY total_regional_revenue DESC;

---------------------------------------------------

-- Question #6: What is the average number of days it takes to close a deal for each business size?
SELECT
  business_size,
  ROUND(AVG(days_to_close), 1) AS avg_days_to_close
FROM tutorial.dunder_mifflin_paper_sales
WHERE business_size IS NOT NULL
GROUP BY business_size
ORDER BY avg_days_to_close DESC;

---------------------------------------------------

-- Question #7: What is the maximum shipping cost for each shipping mode?
SELECT 
  shipping_mode,
  MAX(shipping_cost) AS max_shipping_cost
FROM tutorial.dunder_mifflin_paper_sales
WHERE shipping_mode IS NOT NULL
GROUP BY shipping_mode
ORDER BY max_shipping_cost DESC; 

---------------------------------------------------

-- Question #8: How many total units have been sold for each product?
SELECT 
  product_id,
  product_name,
  SUM(quantity) AS total_units_sold
FROM tutorial.dunder_mifflin_paper_sales
GROUP BY product_id, product_name
ORDER BY total_units_sold DESC;

---------------------------------------------------

-- Question #9: What is the average order price for each payment cycle?
SELECT
  payment_cycle,
  ROUND(AVG((price * quantity) - discount), 2) AS avg_order_price
FROM tutorial.dunder_mifflin_paper_sales
WHERE discount IS NOT NULL 
  AND payment_cycle IS NOT NULL     -- Orders with NULL discount values or NULL payment_cycles are excluded due to missing data.
GROUP BY payment_cycle
ORDER BY avg_order_price DESC;

---------------------------------------------------

-- Question #10: What are the highest and lowest customer ratings recorded?
SELECT 
  MIN(rating) AS lowest_rating,
  MAX(rating) AS highest_rating
FROM tutorial.dunder_mifflin_paper_sales
WHERE rating IS NOT NULL;


---------------------------------------------------
-- SECTION 2: Basic Arithmetic  (Q11–Q13)
---------------------------------------------------


-- Question #11: Calculate the total revenue for each order after including shipping cost. 
SELECT 
  order_id, 
  ROUND((price * quantity + shipping_cost), 2) AS total_revenue_plus_shipping
FROM tutorial.dunder_mifflin_paper_sales
WHERE status = 'COMPLETED'
  AND shipping_cost IS NOT NULL     -- Orders with NULL shipping_cost values are excluded due to missing data.
ORDER BY total_revenue_plus_shipping DESC;

---------------------------------------------------

-- Question #12: Calculate the net revenue for each order, accounting for applied discounts.
SELECT 
  order_id, 
  ROUND((price * quantity - discount), 2) AS net_revenue
FROM tutorial.dunder_mifflin_paper_sales
WHERE status = 'COMPLETED'
  AND discount IS NOT NULL     -- Orders with NULL discount values are excluded due to missing data.
ORDER BY net_revenue DESC;

---------------------------------------------------

-- Question #13: Calculate the average revenue per unit sold for each product. 
SELECT
  product_id,
  product_name,
  ROUND(AVG((price * quantity - discount) / quantity), 2) AS avg_revenue_per_unit
FROM tutorial.dunder_mifflin_paper_sales
WHERE discount IS NOT NULL     -- Orders with NULL discount values are excluded due to missing data.
GROUP BY product_id, product_name
ORDER BY avg_revenue_per_unit DESC;


---------------------------------------------------
-- SECTION 3: Business Scenarios (Q14–Q15)
---------------------------------------------------


-- Question #14: Identify which accounts generate the most revenue, considering price, quantity, and discounts. Aggreate total revenue per account and order from highest to lowest. 
SELECT
  account_id,
  account_name,
  ROUND(SUM((price * quantity) - discount), 2) AS total_revenue
FROM tutorial.dunder_mifflin_paper_sales
WHERE status = 'COMPLETED'
  AND discount IS NOT NULL     -- Orders with NULL discount values are excluded due to missing data.
GROUP BY account_id, account_name
ORDER BY total_revenue DESC;

-- Question #15: Determine the average number of days to ship orders for each shipping region, helping operations spot slow regions. 
SELECT 
  shipping_region,
  ROUND(AVG(days_to_ship), 1) AS avg_days_to_ship
FROM tutorial.dunder_mifflin_paper_sales
GROUP BY shipping_region
ORDER BY avg_days_to_ship DESC;
